faderfox/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length, Optional

from decolab.classes import attributes

cnames = [f'cc{n}' for n in range(1, 25)]
valids = [Optional(), Length(min=2, max=16)]
fields = [StringField(f'CC {n}', validators=valids) for n in range(24)]

@attributes(dict(zip(cnames, fields)))
class ControllersForm(FlaskForm):
    preset = StringField('Preset Name', validators=[DataRequired(), Length(min=2, max=16)])
    submit = SubmitField('Save Preset')

    def get(self, num: int):
        return getattr(self, f"cc{num}")

faderfox/__init__.py
from flask import Flask
from flask import url_for
from faderfox.main.routes import main

app = Flask(__name__)
app.register_blueprint(main)

faderfox/main/routes.py
import pathlib
from flask import url_for
from flask import request
from flask import redirect
from flask import Blueprint
from flask import render_template
from urllib.parse import urlparse

from faderfox.main.forms import ControllersForm
from faderfox.main.dataops import load_preset
from faderfox.main.dataops import store, fetch 
from faderfox.main.dataops import delete_preset
from faderfox.main.dataops import fetch_presets
 

main = Blueprint('main', __name__)

DB = pathlib.Path('persistence/presets.db')

@main.route('/', methods=['GET', 'POST'])
@main.route('/new', methods=['GET', 'POST'])
def new():
    form = ControllersForm(meta={'csrf': False})
    if request.method == 'POST':
        if form.validate():
            data = dict(request.form)
            preset = data.pop('preset')
            transformed = {(int(k.strip('cc'))): ('unassigned' if not v else v) for k,v in data.items()}
            controllers = sorted(transformed.items(), key=lambda items: items[0])
            err = store(DB, preset, controllers)
            return redirect(url_for('main.new', saved=True, name=preset, error=err))
    return render_template('index.html', presets=fetch_presets(DB), form=form, **request.args)


@main.route('/load/<preset>', methods=['GET'])
def load(preset):
    data = load_preset(DB, preset)
    if data:
        form = ControllersForm(data=data, meta={'csrf': False})
        return render_template('index.html', presets=fetch_presets(DB), form=form, saved=False)
    return redirect(url_for('main.new'))


@main.route('/delete', methods=['GET'])
def delete():
    preset = urlparse(request.referrer).path.split('/')[-1]
    if preset and preset != 'new':
        err = delete_preset(DB, preset)
        return redirect(url_for('main.new', deleted=True, name=preset, error=err))
    return redirect(url_for('main.new'))

faderfox/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Custom styles for this template -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
    <title>faderfox pc4 editor</title>
</head>

<body>
    {% block content %}
    {% endblock %}
    <!-- Javascript CDN -->
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.5/umd/popper.min.js" integrity="sha512-8cU710tp3iH9RniUh6fq5zJsGnjLzOWLWdZqBMLtqaoZUA6AWIE34lwMB3ipUNiTBP5jEZKY95SfbNnQ8cCKvA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>  -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    {% block javascript %}
    {% endblock %}
</body>
</html>

faderfox/templates/delete.html
{% block modal %}
<div class="container">
    <div class="row">
        <div class="col-md-12">

            <div class="modal fade" tabindex="-1" id="delete-dialog">
                <div class="modal-dialog">
                    <div class="modal-content">

                       <div class="modal-header"><h3 class=modal-title>PRESETS</h3></div>

                        <div class="modal-body">
                            <center>Delete Current Preset?</center>
                        </div>

                        <div class="modal-footer">
                            <div class="row">

                                <div class="col-sm-6 btn-delete">
                                    <a href="{{ url_for('main.delete') }}"><button type="button" class="btn-modal">Delete</button></a>
                                </div>

                                <div class="col-sm-6 btn-delete-close">
                                    <button type="button" class="btn-modal" data-bs-dismiss="modal">Close</button>
                                </div>
                                
                            </div>

                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}

faderfox/templates/deleted.html
{% block saved %}
<div class="container">
    <div class="row">
        <div class="col-md-12">

            <div class="modal" tabindex="-1" role="dialog" id="deleted-dialog">
                <div class="modal-dialog">
                    <div class="modal-content">

                       <div class="modal-header"><h3 class=modal-title>Presets</h3></div>

                        <div class="modal-body">
                            {% if error %}
                                <center>{{ error }}</center>
                            {% else %}
                                 <center>{{ name }} has been deleted from the database</center>
                            {% endif %}
                        </div>
                        
                        <div class="modal-footer"><button type="button" class="btn-modal" data-bs-dismiss="modal">Close</button></div>

                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}

faderfox/templates/deletedjs.html
<script>
  $(document).ready(function(){
    $("#deleted-dialog").modal("show");
  });
</script>

faderfox/templates/grid.html
{% block grid %}
<div class="grid-container">
   <form method="POST" action="" class="preset-form">
      {{ form.hidden_tag() }}
       <div class="form-group preset-name-field">
          {% if form.preset.errors %}
          {{ form.preset(class="form-control is-invalid") }}
          <div class="invalid-feedback">
              {% for error in form.preset.errors %}
              <span>{{ error }}</span>
              {% endfor %}
          </div>
          {% else %}
            {{ form.preset(class="form-control input-color-override", placeholder="Preset Name", required="required") }}
          {% endif %}
      </div>

      {%for i in range(6)%}
         <div class="block-list block-list-4">

         {%for n in range(4)%}
            {% set field = i*4 + n + 1 %}
            <div class="block-list__item">
                 <div class="form-group cc-field">
                   {% if form.get(field).errors %}
                   {{ form.get(field)(class="form-control is-invalid") }}
                   <div class="invalid-feedback">
                       {% for error in form.get(field).errors %}
                       <span>{{ error }}</span>
                       {% endfor %}
                   </div>
                   {% else %}
                     {{ form.get(field)(class="form-control input-color-override", placeholder=field) }}
                   {% endif %}
                 </div>
            </div>

         {%endfor%}

         </div>

      {%endfor%}

      <div class="form-group">
         <center><button type="submit" class="btn-save">Save Preset</button></center>
      </div>
   </form>
</div>
{% endblock %}

faderfox/templates/index.html
{% extends "base.html" %}
{% block content %}
{% include "navbar.html" %}
{% include "grid.html" %}
{% include "modal.html" %}
{% include "delete.html" %}
{% include "deleted.html" %}
{% include "saved.html" %}
{% endblock content %}

{% block javascript %}
{% if saved %}
    {% include "modaljs.html" %}

{% elif deleted %}
    {% include "deletedjs.html" %}

{% endif %}
{% endblock javascript%}

faderfox/templates/modal.html
{% block modal %}
<div class="container">
    <div class="row">
        <div class="col-md-12">

            <div class="modal fade" tabindex="-1" id="load-dialog">
                <div class="modal-dialog">
                    <div class="modal-content">

                       <div class="modal-header"><h3 class=modal-title>PRESETS</h3></div>

                        <div class="modal-body">
                          <ul>
                            {% for preset in presets %}
                                <li><a class="dropdown-item" href="{{ url_for('main.load', preset=preset)}}"><h5 class="preset-title">{{ preset }}</h5></a></li>
                            {% endfor %}
                          </ul>
                        </div>
                        
                        <div class="modal-footer"><button type="button" class="btn-modal" data-bs-dismiss="modal">Close</button></div>

                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}

faderfox/templates/modaljs.html
<script>
  $(document).ready(function(){
    $("#save-dialog").modal("show");
  });
</script>

faderfox/templates/navbar.html
{% block navbar %}

<h1 class="navbar-brand w-100"><span class="">Faderfox PC4 Preset Editor</span></h1>

<nav class="navbar navbar-expand-lg navbar-dark" id="navstyle">

<!-- Mobile Menu Button ---------------------------------------------->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

<!-- Navigation Links ------------------------------------------------>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto w-100 justify-content-center px-3">
            <li class="nav-item"><a class="nav-link" href="{{ url_for('main.new') }}">New</a></li>
            <li class="nav-item"><a class="nav-link" onclick="$('#load-dialog').modal('show');">Load</a></li>
            <li class="nav-item"><a class="nav-link" onclick="$('#delete-dialog').modal('show');">Delete</a></li>
        </ul>
    </div>
</nav>
{% endblock %}

faderfox/templates/saved.html
{% block saved %}
<div class="container">
    <div class="row">
        <div class="col-md-12">

            <div class="modal fade" tabindex="-1" role="dialog" id="save-dialog">
                <div class="modal-dialog">
                    <div class="modal-content">

                       <div class="modal-header"><h3 class=modal-title>Presets</h3></div>

                        <div class="modal-body">
                            {% if error %}
                                <center>{{ error }}</center>
                            {% else %}
                                 <center>Preset {{ name }} has been saved to the database</center>
                            {% endif %}
                        </div>
                        
                        <div class="modal-footer"><button type="button" class="btn-modal" data-bs-dismiss="modal">Close</button></div>

                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}